redis:
  image: "redis:latest"
  restart: always
  ports:
    - "6379:6379"

influxdb:
  image: "influxdb:latest"
  ports:
    - "8086:8086"

grafana:
  image: "grafana/grafana"
  ports:
    - "3000:3000"
  links:
    - influxdb

diff-exchangesi:
  build: .
  net: "host" 
